### ISSUE TITLE
Use @ as prefix instead.

### ISSUE THREAD

**Issue by tumashu** [p1uxtar/pyim-cangjie5dict#1]
"." is used by wubi dict, cangjie use "@" instead.

**Comment by tumashu** [comment]
by the way, I have add basic cangjie support, you can (setq pyim-default-scheme 'cangjie) for test.

**Comment by a5corpii** [comment]
I have changed the prefix "." to "@".

But I have got none candidate Chinese characters when I set the default-scheme to cangjie (wubi is also the same), so I haven't tested the basic cangjie support which's version is 3 or 5 and more features.
I'll test further when I wake up tomorrow.

**Comment by tumashu** [comment]
安装最新的pyim试试，另外一个问题是，仓颉输入法五个字母的码对应的汉字常用不？pyim需要设置一个最长码，是设置成5还是4？如果设置成5，输入4码的字要用空格选字，如果设置为4，4码的字不用敲空格，但5码的字就无法输入了

**Comment by tumashu** [comment]
要不我添加两个scheme:  cangjie4key 和 cangjie5key?，平常用4key，如遇到生僻字输入，用户切换手动到5key

**Comment by tumashu** [comment]
```
(file (concat dir "pyim-cangjie5.pyim"))

```

这个地方不对

**Comment by tumashu** [comment]
```
安装最新的pyim试试，另外一个问题是，仓颉输入法五个字母的码对应的汉字常用不？pyim需要设置一个最长码，是设置成5还是4？如果设置成5，输入4码的字要用空格选字，如果设置为4，4码的字不用敲空格，但5码的字就无法输入了
```
我仔细测试了一下，五码的汉字可以通过数字键来选择，所以我设置为： 默认4键，减少空格输入，5键的字用数字键选择。

**Comment by a5corpii** [comment]
仓颉默认就是5码，很多字本身取码规则就是2+3，特别是取词，只有少数才是4码。我当初也因为码长和其他问题在仓颉、郑码、山人等之间纠结很久，只能说各个方案之间各有利弊。
不过如果最长5码的话，又不符合五笔的习惯了。

`(file (concat dir "pyim-cangjie5dict.pyim"))`
这一句已经修改了。

函数及代码的部分，还请你多费心。我没系统学过计算机知识，一切还都在自学和摸索中。

**Comment by tumashu** [comment]
如果是少数才是4吗,大部分是5码, 那就比较好说了. 我去更改
